package com.test.java.javatest.폭풍if개선하기;

public enum ORDER_MESSAGE_SEND_TYPE {
	ORDER_DELIVERY_REQUEST,
	ORDER_CANCELED,
	ORDER_DELIVERY_COMPLETED,
	ORDER_DELIVERY_RESERVED,
	ORDER_PICKUP_REQUEST,
	ORDER_PICKUP_RESERVED,
	GIFT_DELIVERY,
	GIFT_PICKUP,
	NONE
}
